name=input("Hey buddy, what's your last name? ")
if (name=="Solomon"):
    print("Congradulations, you have the best name!")
elif (name[0:1]>='A' and name[0:1]<='M' or name[0:1]>='a' and name[0:1]<='m'):
    print("Congratulations, because of the alphabet, you will always be in front!")
else:
    print("rip, cause of the alphabet you will always be towards the end of the line")
input()
print("Hey buddy, why are you still here?")
input()
print("I don't really care. Just remember the x button is up there")
input()
print("Top right.")
input()
print("Remember, if you make an L with your pointer and thumb, then that's your left side.")
print("The right side is the opposite side")
input()
print("Okay, get out of here. I have things to do")
input()
input()
print("Goodnight")
input()
input()
input()
print("One more time and I'm going to have to throw you out")
input()
print("That's it!")
input()